/**
 * The import against a real Workday export and the real catalog.
 *
 * Both inputs are outside the repo — the export holds a student's registration
 * and `static/schedb.json` is regenerated by `pnpm updateData` — so this suite
 * skips itself when either is missing, like `tests/data/realCatalog.test.ts`.
 *
 * To run it, drop a "View My Courses" export at the path below. It asserts only
 * that every enrolled course resolves to exactly one section, which is the claim
 * that would break if Workday changed its column layout or section labelling.
 */
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { Catalog } from '$lib/model/catalog';
import type { SchedbFile } from '$lib/model/schedb';
import { readWorkdayExport } from '$lib/workday';

const EXPORT_PATH = fileURLToPath(new URL('../../../View_My_Courses(2).xlsx', import.meta.url));
const CATALOG_PATH = fileURLToPath(new URL('../../static/schedb.json', import.meta.url));

const available = existsSync(EXPORT_PATH) && existsSync(CATALOG_PATH);

describe.skipIf(!available)('a real Workday export against the real catalog', () => {
  const catalog = new Catalog(JSON.parse(readFileSync(CATALOG_PATH, 'utf8')) as SchedbFile);
  const workbook = () => new Uint8Array(readFileSync(EXPORT_PATH));

  it('resolves every enrolled course to exactly one catalog section', async () => {
    const { matched, unmatched } = await readWorkdayExport(workbook(), catalog);

    expect(unmatched).toEqual([]);
    expect(matched.length).toBeGreaterThan(0);
  });

  it('matches on full section sets, never on a partial one', async () => {
    const { matched } = await readWorkdayExport(workbook(), catalog);
    expect(matched.filter((course) => course.partial)).toEqual([]);
  });

  it('resolves each course to a section the catalog really has', async () => {
    const { matched } = await readWorkdayExport(workbook(), catalog);

    for (const course of matched) {
      expect(catalog.getSection(course.sectionId)).toBeDefined();
      expect(catalog.getCourseIdOfSection(course.sectionId)).toBe(course.courseId);
    }
  });

  it('never picks the same course twice', async () => {
    const { matched } = await readWorkdayExport(workbook(), catalog);
    const courseIds = matched.map((course) => course.courseId);

    expect(new Set(courseIds).size).toBe(courseIds.length);
  });
});
